# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ceb9a46b809e080c2bf7fc3fbb4c6b2150717be5109a00d4e2d2c5ce4d52a49cd316e31956dce44459b14d25bfef3fca2630a89c0e0015631a3a242f12959dc3

test:
  secret_key_base: f10dcae2f61209c174b5ebf959265b0b86a36e8e72c829132c767ddbba303cb4468f119811c472164cdccc6f73385d9e61ca3191c439c3b66d7516a7475d638a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
